Logging: Don't allow getting user info to stop application starting
In certain scenarios (probably due to host contamination) the effective UID of
the running application is not the expected "genenetwork" user, rather, it is
a user on the host system, which leads to the error:

    KeyError: 'getpwuid(): uid not found: 1000'

This commit prevents the application from failing in such a case, but still
logs out such weirdness.